### PR TITLE
Make window-close symbolic consistent with window-maximize

### PR DESCRIPTION
**Pull request by lainsce**
This ensures both have the same optical size and styling. It may feel strange at first, but it's because we're accustomed to the tiny non-consistent icon.

Looks like:
close

### CODE REVIEW

**Comment by fabiozaramella** [comment]
I'd like to hear what @elementary/ux team think about it. I agree that It looks better once you get used to it.

**Comment by cassidyjames** [comment]
It still feels huge to me. I think this is a case of technical equality versus perceptual equality; because the maximize icon has a thinner part an is only on one axis, it needs to be a bit bigger to feel the same weight as the smaller `x` icon.

So I personally don't love this change, as it makes the `x` button way more prominent. It even feels (almost) as prominent as the toolbar buttons in Files, which I think looks wrong here. But I'll leave this one up to actual icon designers like @danrabbit and @micahilbery.

**Comment by fabiozaramella** [comment]
> It still feels huge to me. I think this is a case of technical equality versus perceptual equality; because the maximize icon has a thinner part an is only on one axis, it needs to be a bit bigger to feel the same weight as the smaller `x` icon.
> 
> So I personally don't love this change, as it makes the `x` button way more prominent. It even feels (almost) as prominent as the toolbar buttons in Files, which I think looks wrong here. But I'll leave this one up to actual icon designers like @danrabbit and @micahilbery.

Mmh i don't agree that it looks as prominent as main buttons but I'd like to hear other opinions too. Maybe we can go the other way round and decrease the size of maximize icon to match.

For reference (it's looks good to me, but obviously i'm not an icon designer, I can only give my opinion):
Schermata del 2020-11-04 20 32 33

**Comment by lainsce** [comment]
I could also go the other way and shrink maximize to the same size as close.

**Comment by fabiozaramella** [comment]
> I could also go the other way and shrink maximize to the same size as close.

Yes, please. Would you mind pushing a PR just to check which option is better?

**Comment by lainsce** [comment]
Made the PR, see above.

**Comment by waldyrious** [comment]
Hey @lainsce — for those of us not in the loop, can you share why this was closed?

**Comment by lainsce** [comment]
Was just something I tried out, and didn't get traction between the core developers/designers, so I just closed it.

**Pull request closed without merging**
