### PR TITLE
Credit card

### LINKED ISSUE #258: Credit card icon
Non-symbolic, in at least dialog size. For https://github.com/elementary/appcenter/issues/397

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #258 

- [x] Generic
    - [x] 16px
    - [x] 24px
    - [x] 32px
    - [x] 48px
- [x] Visa
- [x] Mastercard
- [x] American Express
- [x] Discover
- [x] Diner's Club
- [x] JBC
- [x] Union Pay

### CODE REVIEW

**Comment by snwh** [comment]
Looks more like a hotel room key card than a credit card imo

**Comment by cassidyjames** [comment]
I disagree with @snwh (looks like a credit card to me :stuck_out_tongue:) but I think it looks a little squat? Like too tall for its width.

**Comment by btkostner** [comment]
The card strip looks low to me

**Comment by snwh** [comment]
https://www.google.com/search?q=credit+card&tbm=isch

**Comment by cassidyjames** [comment]
https://www.google.com/search?q=credit+card+icon

**Comment by cassidyjames** [comment]
@danrabbit I like, go for the scaling 😄

**Comment by cassidyjames** [comment]
Namespace-wise, would this make sense as like `payment-card`? I imagine could have something like `payment-card-visa` and `payment-card-mastercard` in the future.

**Pull request merged**
