### PR TITLE
Add Inkscape Spray Can Tool

### LINKED ISSUE #715: Spray Can tool
An icon ` tool-spray` for the spray can tool in an app like Inkscape

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65380766-spray-can-tool?utm_campaign=plugin&utm_content=tracker%2F27377189&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F27377189&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Fatih20**
Fixes #715 

This is how the icon look in elementary's light theme
image
This is how the icon look in elementary's dark theme
image

There is another layer where some of the unused ideas and assets used in the process of designing this icon is stored. I will be cleaning them up once it's finalized and approved.

### CODE REVIEW

**Comment by Fatih20** [comment]
> Can you please remove the alignment icons from this pull request since they're included in a different PR?

Done.

**Comment by danrabbit** [comment]
This looks good, if you're ready to clean up the SVG :)

**Comment by Fatih20** [comment]
Done.

**Comment by Fatih20** [comment]
Hold on Dan, I think the paint isn't visible enough on light theme.

**Comment by Fatih20** [comment]
Here I made the paint a dark green instead so it's visible on both theme, also match the spray can color.

This is how the icon look in elementary's light theme
image
This is how the icon look in elementary's dark theme
image

**Pull request merged**
