### PR TITLE
Calligraphy cleanup

### PR DESCRIPTION
**Pull request by Fatih20**
Cleaning up of prematurely merged #909.

### CODE REVIEW

**Comment by danrabbit** [comment]
Looks like you lost the highlight on the ink. Is that intentional?

**Comment by Fatih20** [comment]
> Looks like you lost the highlight on the ink. Is that intentional?

I fixed in the later commit didn't I?

**Comment by danrabbit** [comment]
@Fatih20 it doesn't look like it. I just branched clean

**Comment by Fatih20** [comment]
Whoops, you're right. There, fixed it.

**Pull request merged**
