### PR TITLE
meson: use Meson build system

### PR DESCRIPTION
**Pull request by tintou**
Nobody can stop the hype train 🚄🎉

### CODE REVIEW

**Comment by micahilbery** [comment]
This also fixes #424

**Comment by codygarver** [comment]
Closes #549

**Comment by decathorpe** [comment]
There's still something wrong with the symlinks - when building an RPM I get a ton of these errors:

```
    Symlink points to BuildRoot: /usr/share/icons/elementary/places@2x -> /builddir/build/BUILDROOT/elementary-icon-theme-4.3.1+git180516.111050.adf21c17-2.fc29.x86_64/usr/share/icons/elementary/places
```

Those symlinks should point to the installation location (PREFIX?), not the build directory location (DESTDIR).

**Comment by NikoKrause** [comment]
Hey, the Installation/Build instructions in the README need to be adapted to Meson.

**Comment by tintou** [comment]
@decathorpe Cody pointed me out that it's the reverse that happens in Debian, the package creator then redirect all the symlink as required.

**Comment by decathorpe** [comment]
Well ... how can this be resolved then? RPM doesn't to automatic symlink wrangling.

**Pull request merged**
