### PR TITLE
Change file manager to blue

### PR DESCRIPTION
**Pull request by danirabbit**
Supersedes #812

### CODE REVIEW

**Comment by micahilbery** [comment]
What it looks like in context:
Screenshot from 2019-08-21 14 31 35

**Comment by micahilbery** [comment]
I'm fine with the color change and the larger house on the 32px icon is definitely a nice improvement :+1:

**Comment by jeremypw** [comment]
I would change the imprint to something more generic to indicate "navigating" or "browsing" or "searching", rather than a particular location.

**Comment by Fatih20** [comment]
I agree. Look how the files manager feels out of place in this screenshot.
Screenshot from 2019-08-30 16 58 51

**Comment by Fatih20** [comment]
> I would change the imprint to something more generic to indicate "navigating" or "browsing" or "searching", rather than a particular location.

What do you think of this design? It's supposed to follow the principle used like the appcenter icon where it looks like an actual store. Same thing with videos icon, it looks like an actual video player.
file-manager-eOS-m

**Comment by Fatih20** [comment]
file-manager-eOS-s
Or this maybe?

**Comment by Fatih20** [comment]
file-manager-eOS-mc
What do you guys think?

**Comment by danirabbit** [comment]
Closing since we got in a new files icon and it is blue :)

**Comment by waldyrious** [comment]
> Closing since we got in a new files icon and it is blue :)

For reference: #1147

**Pull request closed without merging**
