### PR TITLE
Make the file icon less bland and more vibrant

### PR DESCRIPTION
**Pull request by Fatih20**
The original design wasn't bad. I'm just thinking that the color could be... better. It just has that taste of bitter like when you're drinking cough syrup. Subjective indeed, any thought?

### CODE REVIEW

**Comment by cassidyjames** [comment]
The current icon is intentionally silver, as it's a system utility.

**Comment by Fatih20** [comment]
What about system settings? The dominant color when you look at it is blue.

**Comment by cassidyjames** [comment]
It has blue because that's the color of switches. :smile: I guess the inset home icon could be blue to sort of evoke that, but I don't really think it's necessary. @elementary/ux thoughts?

**Comment by Fatih20** [comment]
I think that would be great. It's fine if you want it to be silver but right now it looks more like a decayed paper which shouldn't be how we look at opening files.

**Comment by waldyrious** [comment]
I'd expect it to use the same color as the folder icons in Files, tbh.

**Comment by Fatih20** [comment]
What would you say if we just recolour all of the folder? Because the file manager icon looks like a paper that is about to decay, the actual file icon look like a paper that has already decayed for 2 years at least.
folder

**Comment by danrabbit** [comment]
Now that the standard folder is Manila I wouldn’t be opposed to the Files icon using palette blue (or another palette color). Could be fun :)

**Comment by Fatih20** [comment]
So, do you want me to make a recolor based on the sample I've sent?

**Comment by danrabbit** [comment]
@Fatih20 I've proposed #813 for discussion which uses our palette blue color

**Comment by Fatih20** [comment]
I'll start recoloring all of the folder based on that then.

**Comment by Fatih20** [comment]
> @Fatih20 I've proposed #813 for discussion which uses our palette blue color

But do you think that the color of folders icons need to be blue as well like the file manager icon you proposed? If so, I'll start recolor them and post the result for discussion.

**Comment by cassidyjames** [comment]
@Fatih20 I suggest you look at https://github.com/elementary/icons/pull/634 ;)

We used to have blue folders, but moved to manila to better match real-world folders, to make the overall desktop less overwhelmingly blue, and to support potential per-content colors.

**Pull request closed without merging**
