### PR TITLE
Translation mimes

### LINKED ISSUE #225: gettext mimes
Theme doesn't have mimes for `po` (translation files) and `pot` (translation templates). Currently it look like this:

No icon for `po` files and Microsoft PowerPoint template icon for `pot` files.

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #225

- [x] 16px
- [x] 24px
- [x] 32px
- [x] 48px
- [x] 64px
- [x] 128px

### CODE REVIEW

**Comment by TraumaD** [comment]
Is there not supposed to be a 128px version of the translation template?

**Comment by danrabbit** [comment]
Yes, I'm just super lazy. It looks like I haven't done a 128px templates for anything yet so there isn't a scaled ruler haha

**Comment by TraumaD** [comment]
If you don't mind I could go ahead and start making the 128px versions of all the templates and start a new PR.

**Comment by TraumaD** [comment]
@danrabbit I might be able to help you there. I sent you a DM on slack.

**Pull request merged**
