### PR TITLE
Made Wired network icon look like a RJ45 port to match color versions

### PR DESCRIPTION
**Pull request by lainsce**
Possible fix for #667, makes the symbolic versions look like the port, in the orientation used in the color versions.

For comparison:

| Color | Symbolic |
| --- | --- |
| network-wired | network-wired-symbolic |

Screenshot in action:

screenshot from 2018-09-24 12-51-02

### CODE REVIEW

**Comment by waldyrious** [comment]
I'm afraid this makes the icon less intuitive than the current one. If anything, I'd support converging to the same representation by changing the colored versions, rather than the opposite.

**Comment by lainsce** [comment]
@waldyrious Let's wait to see what the elementary UX team has to say.

**Comment by danrabbit** [comment]
I agree that this is a step backward from the current situation. Something to consider as well is that it looks like tethered USB connections also use this namespace. So it's probably not accurate to always use the RJ45 metaphor at all.

**Comment by lainsce** [comment]
Tethered USB connections should use another colored icon/symbolic icon possibly? As it stands, they use the RJ45 colored/symbolic icon, not their own, which might make it strange on that side, actually.

**Comment by lainsce** [comment]
This is a step backward, we discussed a better plan on Slack. Closing.

**Pull request closed without merging**
