### PR TITLE
Apps: Redesign system-software-install

### PR DESCRIPTION
**Pull request by wpkelso**
Related #1151 

Redesign `system-software-install` to separate it from AppCenter branding

### CODE REVIEW

**Comment by micahilbery** [comment]
That little truck is 👨‍🍳👌💋

**Comment by wpkelso** [comment]
I went ahead and did all of the sizes to keep consistency with the other apps, even if they're unlikely to be used

**Review by danirabbit — CHANGES_REQUESTED** [review]
Hey sorry for taking a while to follow up here. This is a super cute little icon. I love that it shows a kind of more "industrial" implication of the package manager versus the app store as well.

My only major complaint is that its much smaller than other icons at its size and where the baseline of the icon is seems to be higher. See for example here:

Screenshot from 2024-06-24 08 14 57

Another thing to watch out for is how highlight gradients fall over the top edges of objects. Look at this for example. You can see how the gradient stop should match up with where that corner stop is:

Screenshot from 2024-06-24 08 18 05

**Comment by wpkelso** [comment]
Oh oops, apparently 'temporary' means permanent. Let me fix that then it will be ready for review again

**Comment by wpkelso** [comment]
Actually ready for re-review now

**Review by danirabbit — CHANGES_REQUESTED** [review]
Looking really good! The smallest sizes are especially cute. Just a few comments here

The border color here is significantly different from the archive file type icon:

Screenshot from 2024-08-16 15 33 06

when you have a rounded shape that contains another rounded shape, make sure that you adjust the radii so that there's consistent spacing around the edges. See the red circle in the first shape and how there's a lot of extra gap compared to the shape on the right?

Screenshot from 2024-08-16 15 37 43

Also for highlight gradients you want the outer stops to be contained inside the stroke and the inner stops should line up with the radius handle of the shape basically

**Review by danirabbit — APPROVED** [review]
Thanks for sticking with it through all the rounds of feedback! These are very cute icons, good job :)

**Pull request merged**
