### PR TITLE
Updated rounded straight-arrowed icons

### PR DESCRIPTION
**Pull request by lainsce**
This should contain all updated straight arrowed icons

### CODE REVIEW

**Comment by danrabbit** [comment]
Can you break this up? It's a little difficult to try to review so many icons at once

**Comment by lainsce** [comment]
I can revert to when it was only 48px icons would that work?

**Comment by lainsce** [comment]
Reverted to only have the 48px icons

**Comment by danrabbit** [comment]
Hey I'm not sure if you saw but after working on the mail-* icons, I changed the arrow shape a bit. Specifically the stem is now thicker

**Comment by lainsce** [comment]
I'll update these to have the new stem soon.

**Comment by lainsce** [comment]
Well, since you started it up before me, and you do it with better quality than me, I'm closing this.

**Pull request closed without merging**
