### PR TITLE
Made the non-symbolic Check Spelling iconset

### PR DESCRIPTION
**Pull request by lainsce**
Made the non-symbolic counterpart to this action iconset, supplementing to the sizes needed.
Fix for issue #540.

It looks like this:
screenshot from 2018-09-28 22 30 49

### CODE REVIEW

**Comment by danrabbit** [comment]
This is a good start, but make sure to check these against the dark stylesheet as well. Notice that the "bold" icon is still visible, but yours are not:
 
screenshot from 2018-09-26 11 46 42 2x
screenshot from 2018-09-26 11 47 43 2x

**Comment by lainsce** [comment]
Will make 'em work on the dark stylesheet soon.

**Comment by lainsce** [comment]
I fixed the dark stylesheet problem, and I simplified the design to look less crowded with only the lowercase a.

**Comment by NikoKrause** [comment]
> Hopefully now they look ok also in the dark.

Lookbook has a dark mode.
https://appcenter.elementary.io/com.github.danrabbit.lookbook/

**Comment by lainsce** [comment]
Hopefully it now looks amazin' and in-grid, ready for merge.

**Review by danrabbit — CHANGES_REQUESTED** [review]
These are still not legible in dark style and don't follow the existing style of similar icons. See:

Screenshot from 2020-10-27 08 51 36@2x

**Comment by lainsce** [comment]
I feel like these could be done better by someone else. I'm closing this.

**Pull request closed without merging**
