### PR TITLE
Remove duplicate contributing instructions

### PR DESCRIPTION
**Pull request by waldyrious**
All of its contents are duplicated in the README.

This was initially raised in #673.

### CODE REVIEW

**Comment by danrabbit** [comment]
I'm going to close this because CONTRIBUTING.md is recommended by GitHub community guidelines. I'd prefer removing the duplicate info from README.md and linking to CONTRIBUTING.md

**Comment by waldyrious** [comment]
No problem, I can update the PR to make the opposite change. Can you reopen it please?

**Comment by danrabbit** [comment]
Sure, sounds good :)

**Comment by waldyrious** [comment]
@danrabbit I've updated the PR. Some of the content of CONTRIBUTING.md was either changed to match edits that had been edited in the README, reworded for clarity, or rearranged to make the content follow a more sequential flow. The gist of the content remains, though -- no information was removed.

Let me know what you think!

**Comment by danrabbit** [comment]
Closing since there are conflicts and there haven't been any updates here in over a year

**Comment by waldyrious** [comment]
@danrabbit apologies for not following up — if I get the chance, I'll recreate this PR.

**Pull request closed without merging**
