### PR TITLE
Made new icons for marking/not marking mail as junk

### PR DESCRIPTION
**Pull request by lainsce**
Made a new iconset for these actions.
Fix for issue #539.

Looks like this:
mark-mail-junk =
screenshot from 2018-09-27 23 11 45

mark-mail-notjunk =
screenshot from 2018-09-27 23 11 56

### CODE REVIEW

**Comment by cassidyjames** [comment]
@lainsce junk is distinct from trash, so I don't think we want to confuse those two.

**Comment by lainsce** [comment]
All the iconsets I've seen online for the junk metaphor use a trashcan or a trash bag with a mail envelope sticking out. :thinking:

**Comment by cassidyjames** [comment]
@lainsce see #539 for icon discussion, as I want to get a consensus on the metaphor before we get too far. :)

**Comment by lainsce** [comment]
Following the discussion, it seems we've arrived in a common ground metaphor, the Octagon.

**Comment by micahilbery** [comment]
I think the exclamation mark is a little inconsistent I would grab the one from `status` / `dialog-error`. Also I think the stroke color on the red is a little dark I would look at the stroke and shadow colors from that icon too as it's also red.

**Comment by lainsce** [comment]
The exclamation mark did indeed come from `status/dialog-error` :grimacing: 
Also, I'm just using the darkest red in the official pallette as is common to use the darkest one.

**Comment by micahilbery** [comment]
I'm talking about the non-symbolic version.

dialog-error

**Comment by lainsce** [comment]
Oh, that one. I'll use it then :smile:

**Comment by danrabbit** [comment]
Please be mindful of the grid

screenshot from 2018-09-27 09 50 39 2x

**Comment by lainsce** [comment]
Now it should look amazin'.

**Comment by danrabbit** [comment]
Some of your nodes are still off:

screenshot from 2018-09-27 16 09 32 2x

Please make sure you're using the same 4 stop gradient for highlights instead of a new 2 stop gradient:

screenshot from 2018-09-27 16 10 42 2x

Also please keep the same shadows from dialog-error instead of inventing a new shadow. Especially since these shadows are a darker and more saturated red and yours are black:

screenshot from 2018-09-27 16 11 59 2x

**Comment by lainsce** [comment]
It seems the war isn't over yet. I'll fight until the end and hopefully win!

**Comment by danrabbit** [comment]
Getting closer! It looks like none of these icons are equilateral

**Comment by lainsce** [comment]
It's a gamble, grid-respecting, or equilaterality :grimacing:

**Comment by danrabbit** [comment]
I think equilateral is probably more important than the diagonals behind at grid corners. Diagonal lines have to be antialised anyways.

Something is really funky with the placement of the exclamation point on your 48px icon. Compare to the right side which is equilateral and the exclamation sits in the same position as dialog-error:

screenshot from 2018-09-27 17 54 26 2x

**Comment by lainsce** [comment]
I'll look into it.

**Comment by lainsce** [comment]
Finished redrawing all of them to be equilateral while also minding the grid.

**Comment by lainsce** [comment]
I'll look into it when I can, but I remember them being equilateral.

**Comment by tintou** [comment]
May I ask why use an octagon?
The only octagon that I know is the stop road sign :man_shrugging:

**Comment by lainsce** [comment]
Octagon in this case is an universal icon in an email setting, just like using a paper airplane for "Send".

**Comment by lainsce** [comment]
:smile:

**Pull request merged**
