### PR TITLE
Optimized (~68% size) icons

### PR DESCRIPTION
**Pull request by lucasmciruzzi**
Optimized icons (using svgo).

The total weight of the icons is about 18MB, and with this optimization is a little below 6MB.

### CODE REVIEW

**Comment by danrabbit** [comment]
Hey thanks for your branch. This is going to take a while to review haha

**Comment by embik** [comment]
This branch is obviously outdated by now, but what's about the optimizations applied here?

**Comment by lucasmciruzzi** [comment]
@embik I could code a script to apply the svgo optimizations in all the files, but that would add a node.js dependency that I think you don't want.

**Comment by embik** [comment]
Maybe we can run svgo during `pre-commit` when it's installed and add a section about it in the readme. I wonder how @danrabbit feels about adding this optimization.

**Comment by danrabbit** [comment]
At the moment, we do have a pre-commit to create plain SVGs and vacuum defs which has resulted in smaller file size over time. I am concerned a bit about using optimized SVG as both @snwh and I have had issues with thumbnailing before, which is pretty inconvenient. If there are additional size optimizations that we can add to the pre-commit and verify aren't destructive, I'm open to that :)

**Pull request closed without merging**
