### PR TITLE
Redesign Phone icons

### PR DESCRIPTION
**Pull request by danrabbit**
because phones look a bit different these days

### CODE REVIEW

**Comment by cassidyjames** [comment]
Another possibility would be the back-side of a generic smartphone, since most of those have at least one camera (often in the top-left) and could give you some more details and color to work with like a flash, antennae lines, etc.

**Comment by NikoKrause** [comment]
No notch

**Comment by danrabbit** [comment]
:man_shrugging: I feel like it's not hard to push another rev when phones stop looking like that but the current flagship generation is all notches. Either way, removed

**Comment by waldyrious** [comment]
The front bezels haven't completely receded yet, notch nonwithstanding (they have become mostly black, indeed). That, plus the fact that an almost completely featureless black rectangle may not be very illustrative, how about lighting up the screen? For example, these are the top results from a google image search for "smartphone icon" I just performed:

screenshot_2018-11-30 smartphone icon - google search

I see several potentially interesting options here. We could go with (1) a white screen, as most of these do; (2) some abstract interface; (3) a color gradient; (4) a solid color. IMO any of these would be more obvious than a black rectangle, and would still represent the current look of smartphones.

**Pull request merged**
