### PR TITLE
Change Files icon to filing cabinet

### PR DESCRIPTION
**Pull request by lainsce**
Uses a file cabinet metaphor, replaces the recolor of the Home folder.

icon

Looks in action:
Screenshot from 2020-08-09 01 28 34
Screenshot from 2020-08-09 01 28 53

~~May need some help with pixel-fitting.~~ Fixed this.

### CODE REVIEW

**Comment by fitojb** [comment]
Yes, please! Thank you for doing this.

**Comment by danrabbit** [comment]
I'm personally not a big fan of the file cabinet metaphor here. It seems a bit more like "archive" to me

**Comment by lainsce** [comment]
The other metaphors were taken up by other OSs... I had either this, or a folder holder. Guess what big OS uses a folder holder... :pensive:

**Comment by danrabbit** [comment]
I'm going to close this as there's been no forward movement from others on UX team and there are a significant amount of :-1:'s here

**Comment by lainsce** [comment]
Understandable

**Pull request closed without merging**
