### PR TITLE
Let CMake do the hard work for us

### LINKED ISSUE #39: Create a build system
Ikey requested this. Cody said he'd do a CMake one. The build system should:
- [x] Generate @2x directory symlinks
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29252310-create-a-build-system?utm_campaign=plugin&utm_content=tracker%2F27377189&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F27377189&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tintou**
Fixes #39

### CODE REVIEW

**Comment by codygarver** [comment]
I feel like it might be bad that we're writing volumeicons directory to /

**Comment by tintou** [comment]
Maybe I should add a flag to install it in "/"

**Comment by codygarver** [comment]
Maybe @danrabbit can tell us if volumeicons are working right now, I'm not sure.

**Comment by danrabbit** [comment]
Yes, volumeicons are working in master

**Pull request closed without merging**
