### PR TITLE
Add Inkscape's Color Picker

### PR DESCRIPTION
**Pull request by Fatih20**
This is how the icons look under elementary's light theme
image
This is how the icons look under elementary's dark theme
image

There is some things that is still in the file that I use in the design process of these icons. I'll be cleaning them up once these are finalized and approved.

### CODE REVIEW

**Comment by Fatih20** [comment]
I also wanted to redesign `color-select-symbolic` and make a `color-picker-symbolic` symlink for it. Is that okay?

**Comment by Fatih20** [comment]
This is how the icons look under elementary's light theme
image
This is how the icons look under elementary's dark theme
image

There is some things that is still in the file that I use in the design process of these icons. I'll be cleaning them up once these are finalized and approved.

**Comment by danrabbit** [comment]
Looks like in this latest revision your highlights are all missing as well

**Comment by Fatih20** [comment]
Can you elaborate? I don't understand your comment. @danrabbit 

> It looks like you have the fill line on a half pixel

What do you mean?

**Comment by danrabbit** [comment]
Sure, as you can see here, the edges of the stroke are not grid aligned and instead sit a half pixel off:

Screenshot from 2020-07-14 15 26 22@2x

**Comment by Fatih20** [comment]
I've lowered by it by half a pixel and fixed the disappearing liquid's highlight.

**Comment by danrabbit** [comment]
Looks good, will merge after cleanup! Thanks :)

**Comment by Fatih20** [comment]
Done.

**Comment by Fatih20** [comment]
Can you close #713 ?

**Pull request merged**
