### PR TITLE
Add System Monitor icon

### LINKED ISSUE #169: Missing utilities-system-monitor icon [$5]
It was removed?

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #169 
- [ ] 16
- [ ] 24
- [ ] 32
- [ ] 48
- [x] 64
- [x] 128

### CODE REVIEW

**Comment by cassidyjames** [comment]
I thought we consciously removed this because we don't ship a system monitor, and so all our icon was doing was rebranding the GNOME app?

**Comment by danrabbit** [comment]
Yeah but it's part of the fd.o icon spec

**Comment by cassidyjames** [comment]
Do we want/need more sizes before we merge?

**Comment by danrabbit** [comment]
Yeah, adding a checklist to description

**Comment by waldyrious** [comment]
> the icon in its github repo is different and nowhere near as cool.

FWIW I actually find that one more pleasing, and also suspect that the increased contrast may make it work better at smaller sizes.

For convenience, here's the image from the repo:

screenshot from 2018-02-25 17-17-50

**Comment by danrabbit** [comment]
We definitely can't steal an icon from a third party app. That would be basically robbing them of their branding.

**Pull request merged**
