### PR TITLE
Actions: Use rounded arrow for browser-download

### PR DESCRIPTION
**Pull request by newhoa**
Completes part of Issue #922 (Make all of the arrows consistent)

### CODE REVIEW

**Comment by newhoa** [comment]
Arrow might be a little too low on 32px, any of these better?

Current

browser-download-pr1-current-too-low

Higher arrow
browser-download-pr1-prop-higher

Higher and wider arrow (I think this one might best?)
browser-download-pr1-prop-higher-wider

Any other feedback would be appreciated. I tried to stick as close as I could to the `go-down` and `document-import` icons.

**Comment by danirabbit** [comment]
@newhoa these look really good, I think you're right about the 32px the higher and wider looks best to me

**Comment by newhoa** [comment]
> @newhoa these look really good, I think you're right about the 32px the higher and wider looks best to me

Ok thanks. Updated, should be good to go if everything else looks good!

**Review by danirabbit — APPROVED** [review]
Fantastic :tada:

**Pull request merged**
