### PR TITLE
bigger 24px battery symbolic

### PR DESCRIPTION
**Pull request by danrabbit**
I'm not sure if this is ridiculous or if it actually makes more sense. Drafting for feedback

Screenshot from 2021-02-23 10 35 09@2x

### CODE REVIEW

**Comment by cassidyjames** [comment]
Well now I can't unsee the battery looking kind of small in the existing icon set. :thinking: I think this would be worth giving a try.

**Comment by danrabbit** [comment]
the more I look at it, the dumber this feels lol Maybe a middle ground

**Comment by danrabbit** [comment]
Screenshot from 2021-02-23 11 07 55@2x

Maybe a little better

**Comment by danrabbit** [comment]
Screenshot from 2021-02-23 16 46 20@2x

Starting to get into the bigger size

**Comment by cassidyjames** [comment]
@danrabbit yeah I like this middle ground!

**Review by micahilbery — APPROVED** [review]
:+1: :battery:

**Pull request merged**
