### PR TITLE
Night light icons

### PR DESCRIPTION
**Pull request by danrabbit**
Proposed icons for Night Light.

### CODE REVIEW

**Comment by Philip-Scott** [comment]
On the latest symbolic icons, one of them is a bit off-centered from the others. You can tell if you toggle the indicator while opened, the "rays" are not aligned :)

**Comment by snwh** [comment]
Any reason why central the circle for the 24px version is off the pixel grid?

**Comment by danrabbit** [comment]
@snwh because the little sun rays are only 1 x 2px so centering would put them off the grid

**Comment by snwh** [comment]
@danrabbit yes, but the inner part of the circle is off the grid as a result

**Pull request merged**
